{"uuid":"9bbca69f-d811-4607-add6-ba292f7b14c8","name":"GET CALL","historyId":"f432a5f7e318dbbb64586faef3d104d7:d41d8cd98f00b204e9800998ecf8427e","status":"broken","statusDetails":{"message":"`cy.request()` failed trying to load:\n\nhttps://gorest.co.in/public/v2/users\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND gorest.co.in\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://gorest.co.in/public/v2/users\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","trace":"CypressError: `cy.request()` failed trying to load:\n\nhttps://gorest.co.in/public/v2/users\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND gorest.co.in\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://gorest.co.in/public/v2/users\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:132747:70)\n    at tryCatcher (http://localhost:63080/__cypress/runner/cypress_runner.js:1807:23)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:4203:37)\n    at tryCatcher (http://localhost:63080/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (http://localhost:63080/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (http://localhost:63080/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromise0 (http://localhost:63080/__cypress/runner/cypress_runner.js:1621:10)\n    at Promise._settlePromises (http://localhost:63080/__cypress/runner/cypress_runner.js:1697:18)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:2392:25)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:63080/__cypress/runner/cypress_runner.js:3486:19)\n    at Promise._then (http://localhost:63080/__cypress/runner/cypress_runner.js:1239:17)\n    at Promise._passThrough (http://localhost:63080/__cypress/runner/cypress_runner.js:4110:17)\n    at Promise.lastly.Promise.finally (http://localhost:63080/__cypress/runner/cypress_runner.js:4119:17)\n    at Object.onRunnableRun (http://localhost:63080/__cypress/runner/cypress_runner.js:162715:53)\n    at $Cypress.action (http://localhost:63080/__cypress/runner/cypress_runner.js:41461:28)\n    at Runnable.run (http://localhost:63080/__cypress/runner/cypress_runner.js:145303:13)\n    at Runner.runTest (http://localhost:63080/__cypress/runner/cypress_runner.js:155245:10)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155371:12)\n    at next (http://localhost:63080/__cypress/runner/cypress_runner.js:155154:14)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155164:7)\n    at next (http://localhost:63080/__cypress/runner/cypress_runner.js:155066:14)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155132:5)\n    at timeslice (http://localhost:63080/__cypress/runner/cypress_runner.js:145643:27)\nFrom Your Spec Code:\n    at Context.eval (webpack:///./cypress/e2e/API TESTING/Httpsrequest.cy.js:3:7)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOTFOUND gorest.co.in\n      at new r (<embedded>:227:405830)\n      at ee.callback (<embedded>:227:411831)\n      at e.callback.s.callback [as _callback] (<embedded>:227:411277)\n      at s._callback.s.callback.s.callback (<embedded>:290:100275)\n      at ee.emit (node:events:514:28)\n      at ee.onRequestError (<embedded>:290:109217)\n      at ClientRequest.emit (node:events:526:35)\n      at TLSSocket.socketErrorListener (node:_http_client:501:9)\n      at TLSSocket.emit (node:events:514:28)\n      at emitErrorNT (node:internal/streams/destroy:151:8)\n      at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"stage":"finished","steps":[{"status":"broken","statusDetails":{"message":"`cy.request()` failed trying to load:\n\nhttps://gorest.co.in/public/v2/users\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND gorest.co.in\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://gorest.co.in/public/v2/users\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","trace":"CypressError: `cy.request()` failed trying to load:\n\nhttps://gorest.co.in/public/v2/users\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND gorest.co.in\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://gorest.co.in/public/v2/users\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:132747:70)\n    at tryCatcher (http://localhost:63080/__cypress/runner/cypress_runner.js:1807:23)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:4203:37)\n    at tryCatcher (http://localhost:63080/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (http://localhost:63080/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (http://localhost:63080/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromise0 (http://localhost:63080/__cypress/runner/cypress_runner.js:1621:10)\n    at Promise._settlePromises (http://localhost:63080/__cypress/runner/cypress_runner.js:1697:18)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:2392:25)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:63080/__cypress/runner/cypress_runner.js:3486:19)\n    at Promise._then (http://localhost:63080/__cypress/runner/cypress_runner.js:1239:17)\n    at Promise._passThrough (http://localhost:63080/__cypress/runner/cypress_runner.js:4110:17)\n    at Promise.lastly.Promise.finally (http://localhost:63080/__cypress/runner/cypress_runner.js:4119:17)\n    at Object.onRunnableRun (http://localhost:63080/__cypress/runner/cypress_runner.js:162715:53)\n    at $Cypress.action (http://localhost:63080/__cypress/runner/cypress_runner.js:41461:28)\n    at Runnable.run (http://localhost:63080/__cypress/runner/cypress_runner.js:145303:13)\n    at Runner.runTest (http://localhost:63080/__cypress/runner/cypress_runner.js:155245:10)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155371:12)\n    at next (http://localhost:63080/__cypress/runner/cypress_runner.js:155154:14)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155164:7)\n    at next (http://localhost:63080/__cypress/runner/cypress_runner.js:155066:14)\n    at <unknown> (http://localhost:63080/__cypress/runner/cypress_runner.js:155132:5)\n    at timeslice (http://localhost:63080/__cypress/runner/cypress_runner.js:145643:27)\nFrom Your Spec Code:\n    at Context.eval (webpack:///./cypress/e2e/API TESTING/Httpsrequest.cy.js:3:7)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOTFOUND gorest.co.in\n      at new r (<embedded>:227:405830)\n      at ee.callback (<embedded>:227:411831)\n      at e.callback.s.callback [as _callback] (<embedded>:227:411277)\n      at s._callback.s.callback.s.callback (<embedded>:290:100275)\n      at ee.emit (node:events:514:28)\n      at ee.onRequestError (<embedded>:290:109217)\n      at ClientRequest.emit (node:events:526:35)\n      at TLSSocket.socketErrorListener (node:_http_client:501:9)\n      at TLSSocket.emit (node:events:514:28)\n      at emitErrorNT (node:internal/streams/destroy:151:8)\n      at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"{\"method\":\"GET\",\"url\":\"https://gorest.co.in/public/v2/users\",\"headers\":{\"authorization\":\"Bearer 025e42553618a6185436d92298b997b3..."}],"start":1731560010415,"name":"Command \"request\"","stop":1731560010062}],"attachments":[],"parameters":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"parentSuite","value":"HTTP Request"},{"name":"host","value":"ASCINLAP60721"},{"name":"thread","value":"pid-31356-worker-main"},{"name":"package","value":"cypress.e2e.API TESTING.Httpsrequest.cy.js"}],"links":[],"start":1731559997353,"fullName":"cypress/e2e/API TESTING/Httpsrequest.cy.js#HTTP Request GET CALL","testCaseId":"f432a5f7e318dbbb64586faef3d104d7","stop":1731560010061}